Replaced `.../decisions/{name}` endpoint with `.../decisions/{snap}` and `.../decisions/{snap}/{app}`
olivercalder/snapd-prompt-api-brainstorming pull request #3
Opened 2023-06-06 18:15 UTC by olivercalder

This change removes the last remaining endpoint using the `name` parameter.  The use of `name` is similar to that in the snapd REST API, but it had been assumed to refer to the snap "label" in the context of prompting, since decisions are stored per-label, e.g. `"snapd.lxd.lxd"`.

Prompt requests are sent using the snap name and app name as separate parameters so that the prompt client need not parse labels into these separate components.  Thus, it makes sense for the endpoint parameters to also follow this pattern, and allow querying all stored decisions for a given snap or for a given app within a given snap.

Additionally, this change introduces new endpoints to delete all stored decisions for a given snap or snap+app, which could be useful if a settings client wants to reset permissions for a given application or if a snap is uninstalled with the `--purge` option.

2023-06-06 23:16 UTC, robert-ancell approved these changes
LGTM

2023-06-07 09:41 UTC, tim-hm requested changes
A few bits of general feedback from me (not just limited to this PR so apologies for crossed boundaires):

1. Maybe replace uppercase HTTP verbs with lowercase HTTP verbs bc they cause errors in renders, ie `post:` rather than `POST:`. Try copy + pasting the contents into https://editor-next.swagger.io/ and it'll raise linting errors + not render the spec.

2. In general, how 'restful' is snapd / how closely do we adhere to the principles of a restful api? I say principles because there is no spec per se just common practices. For example consider `POST /v2/prompting/decisions/{snap}/clear` which in a more restful approach would be `DELETE /v2/prompting/decisions/{snap}` I recommend we stick with `GET`, `POST` and `DELETE` as `PUT`, `PATCH` because in practice I find the latter verbs add confusion whereas the intentions behind `GET/POST/DELETE` are pretty clear.

3. If we want prompting available outside of snaps then how would this PR manage those? I assume the challenge is a snap may have multiple binaries ... perhaps an alternative approach is to save the rule against the full path to the exectuable and pass that in the request body? Something like:

```json
{
   "bin": "/snap/signal-desktop/current/opt/Signal/signal-desktop`
}
```

4. How does snapd identify the uid for incoming requests? For example: `GET /v2/prompting/requests` does this return all requests for all users, or is it expecting the UID in say the request body? Alternatively, could snapd create a socket inside `/run/user/UID/prompting.socket` so that the UID is explicity in the path and only something running in the user session can bind to that?

5. My last comment is I think we want to keep the API/request bodies/permissions as simple as we can at this stage. I'd like to get to a working preview with a simpler API to get some feedback / see how it works in practice. I think if we go too complex from the start it'll take longer to implement, be harder to debug and then hard to refactor. Whereas if we get a true 'mvp' out asap then we can iterate forward from that.

2023-06-08 17:23 UTC, olivercalder commented
Thanks for the feedback @tim-hm !

>     1. Maybe replace uppercase HTTP verbs with lowercase HTTP verbs bc they cause errors in renders, ie `post:` rather than `POST:`. Try copy + pasting the contents into https://editor-next.swagger.io/ and it'll raise linting errors + not render the spec.

Thanks for the suggestion, I'll give the lint checker a try.  The current [snapd REST API](https://snapcraft.io/docs/snapd-rest-api) uses uppercase verbs, so I think I will stick with them here, but @mvo5 can advise if otherwise.

>     2. In general, how 'restful' is snapd / how closely do we adhere to the principles of a restful api? I say principles because there is no spec per se just common practices. For example consider `POST /v2/prompting/decisions/{snap}/clear` which in a more restful approach would be `DELETE /v2/prompting/decisions/{snap}` I recommend we stick with `GET`, `POST` and `DELETE` as `PUT`, `PATCH` because in practice I find the latter verbs add confusion whereas the intentions behind `GET/POST/DELETE` are pretty clear.

Currently, the snapd API uses only `GET`, `PUT`, and `POST`, with `PUT` used only once: `PUT /v2/snaps/{name}/conf`. (@mvo5 perhaps we should consider adding a POST method here as an alias to PUT, and encourage not to use PUT in the future?). I very much like the idea of using `DELETE` for deleting stored decisions, rather than a separate endpoint. `DELETE` is not yet a recognized verb in the snapd API, but it shouldn't be too difficult to add it as part of a PR which adds (initially unimplemented) prompting endpoints to snapd.

Possibly `UPDATE` could be used too, but I think using `POST` on `/v2/prompting/decision/{id}` is fine to update a particular decision, since there's no other possible meaning on that endpoint --- `POST`ing to `/v2/prompting/requests/{id}` should only be accepted for requests which have not yet received a response, and should not be interpreted as updating a previously stored decision.
 
>     3. If we want prompting available outside of snaps then how would this PR manage those? I assume the challenge is a snap may have multiple binaries ... perhaps an alternative approach is to save the rule against the full path to the exectuable and pass that in the request body? Something like:

Since this is proposed extensions to the snapd API, and prompting decisions would be managed entirely by snapd, I'm not sure if/how snapd would need to care about prompting for non-snaps. I'd rather not use the path to the snap binary itself, since snap revisions complicate this (my understanding is binaries are usually run with the actual revision in the path, not the `current` alias, and we presumably want to preserve prompt decisions across snap refreshes).

From a client point of view... again I assume clients are talking directly with snapd, rather than with apparmor or the kernel, so I'm not sure the format of requests/responses for clients need to account for non-snaps.

>     4. How does snapd identify the uid for incoming requests? For example: `GET /v2/prompting/requests` does this return all requests for all users, or is it expecting the UID in say the request body? Alternatively, could snapd create a socket inside `/run/user/UID/prompting.socket` so that the UID is explicity in the path and only something running in the user session can bind to that?

My understanding (@mvo5 please confirm) is that the snapd API can already determine the UID of incoming connections, so this should be fine. But that's true, do we want a separate endpoint for each UID, so that multiple clients can have open connections at the same time? I would think that may mean making all the prompting endpoints of the form `/v2/prompting/{UID}/...` instead, which I don't love, but I'm not sure if this is viable otherwise. Can multiple connections be open on the same socket at the same time, and is it possible to selectively send information to one particular connected client at a time?

>     5. My last comment is I think we want to keep the API/request bodies/permissions as simple as we can at this stage and we can roll out more sophistication as things come together. I'd like to get to a working preview with a simpler API to get some feedback / see how it works in practice. I think if we go too complex from the start it'll take longer to implement, be harder to debug and then hard to refactor. Whereas if we get a true 'mvp' out asap then we can iterate forward from that.

I think this is a good idea, particularly on the client side. Much of the backend for permissions is already ready to go, so that shouldn't be a problem, but I'm very happy to have a mvp client only ever send back yes/no information with defaults in the other response parameters.

Regarding other parts of the API we could perhaps ignore for now, my inclination is to forget about all the `/v2/prompting/decisions**` endpoints for now and just focus on `/v2/prompting/requests**`. The former is really meant for settings clients which allow accessing/modifying previous decisions, and we care much more about the prompting clients at the moment. How does this sound to others?

2023-06-08 19:33 UTC, tim-hm commented
Many thanks for the detailed response @olivercalder :pray: 

Ref 1 - I defo wouldn't change the snapd  docs! I was just referring specifically to the format that the swagger UIs are expecting.

Ref 3 - I know we discussed this ... I just can't recall what the outcome was :thinking: :disappointed: 

Ref 4 - If snapd can tell that'd be ace! I also wonder if exposing the socket in `/run/user/UID/snapd-prompting.socket` would just be a useful thing to do as well because then we can limit permissions to that user. Anyways sounds like something on the snapd side to discuss!

Ref 5 - Yes agree. We'll know more when we have an API for testing and then we should have a better sense of how the api structure can improve as well.

2023-06-08 22:31 UTC, olivercalder commented
Another thing to consider here: The `label` which is currently used by the prompting backend in snapd uses the apparmor "label" (e.g. `snap.lxd.lxd`). This is what snapd receives from apparmor when a new request is required. I think this in general maps to `snap.{snap}.{app}`, but I would need confirmation if that is always the case (@mvo5 or @jrjohansen could perhaps confirm?). If so, snapd can convert that label to `snap` and `app` parameters and use them for everything else, but if not, we may need to continue using a single `label` or `name` field to identify the application causing a request.

2023-06-09 17:57 UTC, merged

2023-08-17 08:17 UTC, jrjohansen commented
@olivercalder TLDR yes the label generally lines up with the apparmor profile name (longer explanation below). In the case of snap based profiles it is snap.{app}. snap.snap.seems to be reserved for snap components. Atm this is all you need to worry about.

Eg. An aa-status from one of my machines showing a set of loaded profiles and their associated modes. The mode is the trailing (enforce), you won't get that in the label reported as part of the apparmor messages.

```
snap.snap-store.ubuntu-software-local-file (enforce)
snap.skype.skype (enforce)
snap.snap-store.snap-store (enforce)
snap.snap-store.ubuntu-software (enforce)
snap.freecad.pip (enforce)
snap.freecad.cmd (enforce)
snap.freecad.freecad (enforce)
snap.firefox.firefox (enforce)
snap.openscad.openscad (enforce)
snap.snap-store.hook.configure (enforce)
snap.firefox.geckodriver (enforce)
snap.skype.hook.configure (enforce)
snap.freecad.hook.configure (enforce)
snap.firefox.hook.connect-plug-host-hunspell (enforce)
snap.cups.lpc (enforce)
snap.firefox.hook.configure (enforce)
snap.cups.lpstat (enforce)
snap.cups.lprm (enforce)
snap.firefox.hook.post-refresh (enforce)
snap.firefox.hook.disconnect-plug-host-hunspell (enforce)
snap.cups.reject (enforce)
snap.cups.lpadmin (enforce)
snap.cups.lpq (enforce)
snap.cups.lpr (enforce)
snap.cups.lpoptions (enforce)
snap.cups.lpinfo (enforce)
snap.cups.lp (enforce)
snap.chromium.chromedriver (enforce)
snap.cups.ipptool (enforce)
snap.cups.cupsreject (enforce)
snap.chromium.chromium (enforce)
snap.cups.ippfind (enforce)
snap.cups.ippeveprinter (enforce)
snap.cups.cupsdisable (enforce)
snap.cups.driverless (enforce)
snap.cups.cupstestppd (enforce)
snap.cups.cupsfilter (enforce)
snap.cups.cupsctl (enforce)
snap.cups.gs (enforce)
snap.cups.cupsenable (enforce)
snap.chromium.hook.configure (enforce)
snap.cups.cupsd (enforce)
snap-update-ns.firefox (enforce)
snap.cups.cupsaccept (enforce)
snap-update-ns.snap-store (enforce)
snap.cups.cups-browsed (enforce)
snap-update-ns.chromium (enforce)
snap.cups.accept (enforce)
snap-update-ns.skype (enforce)
snap.cups.cancel (enforce)
/snap/snapd/19457/usr/lib/snapd/snap-confine (enforce)
/snap/snapd/19457/usr/lib/snapd/snap-confine//mount-namespace-capture-helper (enforce)
/snap/snapd/19361/usr/lib/snapd/snap-confine (enforce)
/snap/snapd/19361/usr/lib/snapd/snap-confine//mount-namespace-capture-helper (enforce)
snap-update-ns.freecad (enforce)
snap-update-ns.cups (enforce)
snap-update-ns.openscad (enforce)
libreoffice-soffice (complain)
libreoffice-soffice//gpg (enforce)
/usr/bin/evince-thumbnailer (enforce)
/usr/bin/evince-previewer (enforce)
/usr/bin/evince-previewer//sanitized_helper (enforce)
/usr/bin/evince (enforce)
/usr/bin/evince//sanitized_helper (enforce)
/usr/sbin/cupsd (enforce)
/usr/sbin/cupsd//third_party (enforce)
/usr/lib/cups/backend/cups-pdf (enforce)
tcpdump (enforce)
virt-aa-helper (enforce)
libvirtd (enforce)
libvirtd//qemu_bridge_helper (enforce)
/{,usr/}sbin/dhclient (enforce)
/usr/lib/connman/scripts/dhclient-script (enforce)
/usr/lib/NetworkManager/nm-dhcp-helper (enforce)
/usr/lib/NetworkManager/nm-dhcp-client.action (enforce)
man_groff (enforce)
man_filter (enforce)
/usr/bin/man (enforce)
libreoffice-xpdfimport (enforce)
/usr/lib/snapd/snap-confine (enforce)
/usr/lib/snapd/snap-confine//mount-namespace-capture-helper (enforce)
nvidia_modprobe (enforce)
nvidia_modprobe//kmod (enforce)
/usr/sbin/cups-browsed (enforce)
libreoffice-oosplash (complain)
lsb_release (enforce)
libreoffice-senddoc (enforce)
swtpm (enforce)
```

There are two wrinkles to be aware of but I don't believe you need to deal with them atm
1. AppArmor supports an internal stacking/bounding so that the label can be a compound label which is a combination of multiple profiles. An example is
```
$ ps -Z
LABEL                               PID TTY          TIME CMD
unconfined                         4773 pts/0    00:00:00 bash
/usr/bin/man//&unconfined (enforce) 2940199 pts/0 00:00:00 man
/usr/bin/man//&unconfined (enforce) 2940207 pts/0 00:00:00 pager
unconfined                      2940260 pts/0    00:00:00 ps
```

The ```/usr/bin/man//&unconfined``` mean the task is confined by two separate profiles both ```/usr/bin/man``` and ```unconfined```. The ```//&``` separator will always indicate this situation.

2. AppArmor has namespacing and it is possible to get a profile name like ```:ns1://snap.skype.skype```.

Whether you get a context (label + additional information like the mode), a simple label that directly maps to a profile name, or a compound label will depend on the interface used, and even the component of the interface.

For the notification interface: The subject label will always be a simple label (is the profile name). It could contain namespacing information IF and only IF notifications are setup to monitor sub namespaces. snapd is not currently doing this I don't think it will any time soon.

For the object label it is possible that it will contain namespace information if the target task is in another namespace. There are caveats here but at this time you shouldn't have to worry about this.